server:
  port: 8097
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    instance-id: limits-service-instance
spring:
  cloud:
    config:
      discovery:
        enabled: true
      name: config-service
      enabled: false
  application:
    name: limits-service
limit:
  min: 10
limit:
  max: 5000
