server:
  port: 8097
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@eureka-service:8761/eureka/
  instance:
    instance-id: limits-service-instance
spring:
  cloud:
    config:
      uri: http://localhost:8096
      discovery:
        enabled: true
      name: config-service
  application:
    name: limits-service
limit:
  min: 1
  max: 10000
